export const SIGNUP = "SIGNUP";
export const CREATE_EMAIL = "CREATE_EMAIL";
export const CREATE_PASSWORD = "CREATE_PASSWORD";
export const CREATE_NAME = "CREATE_NAME";
export const CREATE_COLLEGE = "CREATE_COLLEGE";
export const CREATE_PHONE = "CREATE_PHONE";
export const CREATE_GENDER = "CREATE_GENDER";
export const CREATE_PROFILE_PIC = "CREATE_PROFILE_PIC";
export const CREATE_CASTE = "CREATE_CASTE ";
export const CREATE_SKILLS ="CREATE_SKILLS";
export const CREATE_TYPE ="CREATE_TYPE"


export const ADMIN_CREATE_EMAIL = "ADMIN_CREATE_EMAIL";
export const ADMIN_CREATE_PASSWORD = "ADMIN_CREATE_PASSWORD";
export const ADMIN_CREATE_NAME = "ADMIN_CREATE_NAME";
export const ADMIN_CREATE_PROFILE_PIC = "ADMIN_CREATE_PROFILE_PIC";
export const ADMIN_CREATE_PHONE = "ADMIN_CREATE_PHONE";
